name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js 20
        uses: actions/setup-node@v5


      - name: Create Release
        id: create_release
        uses: actions/create-release@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release created automatically.
          draft: false
          prerelease: false
