name: Versioning

on:
  push:
    tags:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Docker
        uses: actions/setup-python@v2

      - name: Run versioning
        run: |
          docker run --rm -v $PWD:/app -w /app python:3.7-slim pip install bumpversion
          docker run --rm -v $PWD:/app -w /app python:3.7-slim bumpversion --commit --tag
          sed -i "s/version='.*'/version='$(git describe --tags --abbrev=0 | cut -c 2-)'/g" setup.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add setup.py
          git commit -m "Update version in setup.py"
          git push
