name: Versioning

on:
  push:
    tags:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
          architecture: x64

      - name: Install dependencies
        run: |
          pip install bumpversion  # Or any other required dependencies

      - name: Bump version
        run: bumpversion --commit --tag  # Adjust this command according to your versioning tool/script

      - name: Update version in setup.py
        run: |
          sed -i "s/version='.*'/version='$(git describe --tags --abbrev=0 | cut -c 2-)'/g" setup.py

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add setup.py
          git commit -m "Update version in setup.py"
          git push
